@echo off
mode 800
color 0E                                                           
:loop                                                           
echo "          @@@@*                                            "
echo "      @@@@@@@@*                                            "
echo "           @@@*                                            "
echo "           @@@*                                            "
echo "           @@@*                #&&&/                       "
echo "           @@@*             (##&(#                       "
echo "                            #(#%*,%(                       "
echo "                       *    ,%,. ,#*                       "
echo "                        /   ,(*####                        "
echo "                       .  ..((#(%                          "
echo "                         .%%%(#%                           "
echo "                         ,#%/#%#                           "
echo "                     , ..#&%%%(%                           "
echo "                       .%&%%###                            "
echo "                       .*%##(##                            "
echo "                       . *(###%%  (%%,                     "
echo "                      .*  .*(/ *,&%(##/                    "
echo "                     %%%&%@@/  %#,                         "
echo "                     (%%%&&@@@@*                           "
echo "                      /&%%&&&@@@                           "
echo "              #%%      .&&&&@@@@,                          "
echo "             /#%@&&%#    &&&&@@@@                          "
echo "             /&&@%&%%%@%% &&&&@@@#                         "
echo "            &&@     &&&%&%%&&&@@@@                         "
echo "            @@           &&&&&@@@@                         "
echo "                            &@@@@                          "
echo "                            %%@@                           "
echo "                           &&&@@                           "
echo "                          .%&&@@                           "
echo "                          %%@&@@                           "
echo "                         (,&&@@                            "
echo "                         /%%&%%&%%                         "
echo "                         %&@@%(%&@                         "
echo "                                                           "
echo "                                                           "
echo "                                                           "
ping localhost -n 1 -w 250 >nul
cls
echo "                                                           "
echo "                                                           "
echo "                                                                               "
echo "                                                           "
echo "      &@@@@@@@@,                                           "
echo "     (@@@@  @@@@                                           "
echo "            @@@&                                           "
echo "         @@@@@                                             "
echo "      &@@@@/                 *%%&&%                        "
echo "     @@@@@@@@@@@&           ,(#&%/(                        "
echo "                            ((#%*.%#                       "
echo "                            /% . ,#                        "
echo "                        .   **(###                         "
echo "                          ,((((%%#                         "
echo "                        . %###(##(   ,*/                   "
echo "                     .(#.%#####((#,                        "
echo "                    #  %%%#((#### (                      "
echo "                    (/ (((#.###&%%#(,                      "
echo "                    *  /((####/ %&&                        "
echo "                     ( */((#(#(                            "
echo "                    .  .(/((%##                            "
echo "                    ./ */%@@@@                             "
echo "                     %%&&&&@@&&&&                          "
echo "                      /%&&&&&&&&&&&&                       "
echo "                       %&&&&&&&&&&&&&@(                    "
echo "                       %&&%@#//%%%%&&&@@                   "
echo "                       #%%%&&&&&&&@@@@&                    "
echo "                    #(%@%&&&&@@@&                          "
echo "                      #&&@@,                               "
echo "                    (%#%&@@                                "
echo "                   &&&@&&%                                 "
echo "                  &&@@@@,.                                 "
echo "                %%&@@@@                                    "
echo "               %%&@@&                                      "
echo "             .*/&&@@                                       "
echo "             *%&%%%%                                     "
echo "                   .*%*                                    "
echo "                                                           "
echo "                                                           "
echo "                                                           "
ping localhost -n 1 -w 250 >nul
cls

echo "                                                           "
echo "                                                           "
echo "                                                                               "
echo "                                                                               "
echo "                                                           "
echo "                                                           "
echo "      @@@@@@@@@@                                           "
echo "     #@@@*  #@@@                                           "
echo "         &@@@@@&                                           "
echo "         @@@@@@@            /%%%%&(                        "
echo "     ,@@@    @@@%          (##%#%                        "
echo "      @@@@@@@@@@           #(%##,(&                        "
echo "                           .#.  ./#                        "
echo "                        #  , . #(%*/                       "
echo "                   /,.  ...,/(,(  (                      "
echo "                /  .**,#((/(((#%(#( (                      "
echo "                  ,##%%%#,(/(#(##%(((                      "
echo "                  *   (##/.(/###&%#%/                      "
echo "                  *   /(,*,,###. %%%.                      "
echo "                 . /  /// (.((#                            "
echo "                   ./% */.(#/#(                            "
echo "                     (/ /(*,###                            "
echo "                    /,#&@@@@@&.                            "
echo "                      %%%&&@&@&&%%                         "
echo "                     .%%&%&&&&&&&&&&&&                     "
echo "                     %%&&&&@*&&&&&&&&&&&                   "
echo "                     %%&@@@       %%&&@@(                  "
echo "                    %&&@@@       %%%&&@                    "
echo "                   %&@@@&       %%@&@                      "
echo "                 #%&&@@       (%%&&                        "
echo "               %%@@@@.       %%@@@                         "
echo "             %&%%@@.       ./(%@                           "
echo "           &%&@&          **(#%%,                          "
echo "         #%@@@&               ((#%                         "
echo "       (,((%@                    #%&                       "
echo "       %%&                                               "
echo "        ,/#@                                               "
echo "         *#%&                                              "
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "                                                           "
ping localhost -n 1 -w 250 >nul
cls

echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "          @@@@@                                            "
echo "         @@@@@@                                            "
echo "       @@@  @@@                                            "
echo "     @@@&,,,@@@,,           #%&&&&@                        "
echo "     @@@@@@@@@@@@          ((##&%*(                        "
echo "            @@@            .#(,,./#                        "
echo "                               ,/#                         "
echo "                             ./%,                          "
echo "                   .    (../#%##(                          "
echo "                 , . *#///%%%## ,(                         "
echo "                    *((&%%%((#%%&*#                        "
echo "                      /# / /###&&%#                        "
echo "                   ,  *//,/,#(# (%                         "
echo "                    * .//.(#(##                            "
echo "                   , . ///.*(##                            "
echo "                    , */..,,#.                             "
echo "                     %*#%@@@@@                             "
echo "                     #%%%&%&@&&&                           "
echo "                      %%%&&&&&&&&&                         "
echo "                      %%&&&&&&&&&&&&                       "
echo "                     %%&&&@#  ,&&&&&&@                     "
echo "                     &%%&@%      &&%&@&/                   "
echo "                 .%%&&&%@@        %&@&@                    "
echo "     ....*%%%&&&&&%%&&&@&         %%@@.                    "
echo "     ,(/@@@&@&&&&&&@&&(           %&@@                     "
echo "    //*&@@/                       %@@,                     "
echo "    *#                           *%&&%                     "
echo "    (&                           (%@&@                     "
echo "                                 .#&&%                     "
echo "                                 //(%%##(##                "
echo "                                 #(####(*.                 "
echo "                                                           "
echo "                                                           "
ping localhost -n 1 -w 250 >nul
cls
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "      @@@@@@@@@@                                           "
echo "      @@@(                                                 "
echo "     .@@@@@@@@@&                                           "
echo "       (@   @@@@(           #%%&&&                         "
echo "       .@   (@@@*          ((#&&((                         "
echo "      @@@@@@@@@#          .((##,,#                         "
echo "                            *   *%                         "
echo "                          ,(((#%%                          "
echo "                           .,%@%                           "
echo "                        ..,(((#/                           "
echo "                      (,*(#((#(                            "
echo "                  / ..*#&&%%#(%                            "
echo "                    ..*%((#((((                            "
echo "                     /((/#/,((*                          "
echo "                      ,((/(##(  /,                         "
echo "                       .,#/#(/                             "
echo "                     %#(   (#                              "
echo "                     %%%%%&/%@                             "
echo "                      .%%%%&&&@                            "
echo "                       %%&&&&&&@                           "
echo "         %*            %%&&&&&&&@                          "
echo "        / /#%&%*       %%&@@&&&&@@                         "
echo "       ///#(%&&&&%%%%%&%&&&@.%&&&@&                        "
echo "      *#&.    .&&%%%%%&&&&&/ ,%%&@@@                       "
echo "      /&             ,#&&&@   ,%&&@                        "
echo "                              #%&@&                        "
echo "                              ,&%@&                        "
echo "                              .&&&@                        "
echo "                              .&&%&*                       "
echo "                               %&&%@                       "
echo "                               (/@%&*                      "
echo "                               (((/(/((%%                  "
echo "                                (                          "
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "                                                           "
echo "                                                                                                                                                                                                                                cls
ping localhost -n 1 -w 250 >nul
cls

goto loop
